version: "3.7"
services:
  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:5001
    networks:
      - processor-net

  minio:
    container_name: "minio"
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: santiago
      MINIO_ROOT_PASSWORD: santiago
    volumes:
      - minio-data:/data
    networks:
      - processor-net
    command: server --console-address ":9001" /data

networks:
  processor-net:
    driver: bridge

volumes:
  minio-data: